# Generated by Django 2.1.2 on 2018-11-21 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('average_grade', models.FloatField()),
                ('median', models.FloatField()),
                ('max_grade', models.FloatField()),
                ('number_of_solutions', models.IntegerField()),
                ('questions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('russian_title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('hash_str_id', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_link', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('material_viewed', models.FloatField()),
                ('users_watched', models.FloatField()),
                ('hash_str_id', models.CharField(max_length=50)),
                ('is_most_viewed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hash_str_id', models.CharField(max_length=50)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadDate')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Week'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Test'),
        ),
    ]
